### ISSUE TITLE
Cannot block 1.7 due invalid version number

### ISSUE THREAD

**Issue by JosGCS** [hyperdefined/BungeeBlockVersion#39]
Your plugin at Spigot page said that plugin works from 1.7 to 1.20 but when i want to block version number from 0 to 46, it says "Version # is NOT a valid version number! Ignoring this version."

**Comment by hyperdefined** [comment]
Bungeecord only supports 1.8+ and above, hence why it's not listed.

https://github.com/SpigotMC/BungeeCord/blob/master/protocol/src/main/java/net/md_5/bungee/protocol/ProtocolConstants.java#L10

**Comment by JosGCS** [comment]
I'm using FlameCord (BungeeCord fork) that supports +1.7 and your GitHub page says "Minecraft 1.7-1.20"

**Comment by hyperdefined** [comment]
I really don't like to support paid closed source software like that, but I'll add it. The 1.7-1.20 was a typo, I apologize. I create this page forever ago.

Can you tell me which versions (protocol numbers) you are trying to block? 0 to 46 includes snapshots, which should not matter. It should only support major versions.
