### ISSUE TITLE
Using version 1.3.2 says there is a newer version + no blocking

### ISSUE THREAD

**Issue by Uharn** [hyperdefined/BungeeBlockVersion#7]
Hi there i tryied 1.3.2 but:
-Message on startup:
[13:22:42 INFO]: Enabled plugin BungeeBlockVersion version 1.3.2 by hyperdefined
[13:22:42 INFO] [BungeeBlockVersion]: There is a new version available! Please download at https://www.spigotmc.org/resources/bungeeblockversion.84685/

-I havent touched the config file yet so all clients should be rejected right?
i tried both 1.17.1 client and 1.18 client and they were not blocked by the proxy

Using 1.18 Waterfall : https://papermc.io/api/v2/projects/waterfall/versions/1.18/builds/462/downloads/waterfall-1.18-462.jar

**Comment by hyperdefined** [comment]
Woops, look like I messed up with the versions. I will fix this.

I will also take a look at the plugin not blocking!

**Comment by hyperdefined** [comment]
The latest release has fixed both of these problems. Please update!

https://github.com/hyperdefined/BungeeBlockVersion/releases/tag/1.3.3
